project:
  type: book
  output-dir: docs

book:
  title: "SGM Network Study Dataset"
  author: "Seungju Kim"
  date: last-modified
  chapters:
    - index.qmd
    - 1_import.qmd
    - 2_ego_var.qmd
    - 3_alter_var.qmd
    - 00_news.qmd
  repo-url: https://github.com/follhim/sgm_networks_study
  repo-actions: [issue, source]

format:
  html:
    number-depth: 2
    theme:
      light:
      - lumen
      dark:
      - darkly