# Preface {.unnumbered}

The purpose of this website is to document the data cleaning workflow for the **SGM Network Study Dataset**.

This website contains the full data cleaning process from start to finish. The completed dataset can be found in a secure **Box** folder only accessible to approved researchers at the __Ecologies of Liberation Lab__ at University of Illinois. 

As an ego network dataset, our data cleaning and scoring also contains uncommon workflows to score and prepare network data. 

You can also find notes from the latest edits on GitHub. 

:::callout-important
All code and data are processed locally. At no time is data stored on GitHub, even temporarily using memory.
:::

## How does it work?

1.  This data cleaning workflow is performed locally on a laptop.
2.  Each phase is separated by its own R script file (`.qmd` file)
3.  Thus, each R script *chapter* reflects the actual underlying code used to clean and process data. 

> This means that you can also directly suggest edits or corrections **online** (see section below) which will be reflected in the data cleaning workflow.

4.  Everytime the R code is changed or updated, GitHub will track and contain a comment (user must provide) that denotes what changes were made. 

## Spot any errors?
Open an issue in the corresponding chapter you are in. You can find the "*Report an issue*" GitHub button on the **top right** of every page. From there, you can detail what the problem is, and someone will work to resolve the issue. 

Tracking and resolving through **issues** in GitHub is highly recommended as they are tracked and naturally logged into the history of changes/updates to the larger data cleaning workflow. This is crucial for returning to previous issues.

## Progress?

You can track current unresolved and resolved issues [here](https://github.com/follhim/sgm_networks_study/issues). 